Add TreeNode, Tree, and related Visitor classes together with test files
cagdasgerede/JT-diff pull request #1
Opened 2016-12-29 20:48 UTC by serdarkacka

Package `jtdiff.util` contains `TreeNode`, `Tree`, and related `Visitor` classes.
Package `jtdiff.util.tests` contains unit tests testing `TreeNode` and `Tree` classes. JUnit 4 is required to run the unit tests.

2016-12-29 21:15 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +
Remove the unnecessary whitespace.

2016-12-29 21:45 UTC, cagdasgerede requested changes
Minor comments (mostly formatting related)

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +
[minor] Remove the extra whitespace

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +
[minor] Remove extra whitespace

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +
[minor] remove extra newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestPreorderTraversal.java
> +
remove extra whitespace

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestFatherOf.java
> +	 * Father of root should be None
None => null

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove extra newlines

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove extra newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove newlines

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/TreeNode.java
> +
remove extra newlines

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/TreeNode.java
> +
remove newlines

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +			throw new IllegalArgumentException("No father node at the given position: " + descendantPosition);
lines should be <=80 characters

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +	 * @throws IllegalArgumentException
IllegalArgumentException if no node found at the descendantPosition

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove extra newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove extra newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/Tree.java
> +
remove extra newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/TreeNode.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestAncestorIterator.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestNodeAt.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestNodeAt.java
> +		// Testing getting a node from the tree by its preorder position
remove this comment and extra newlines

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestFatherOf.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestPreorderTraversal.java
> +		String[] expected = new String[] {"label: A, preorder_position: 1",
move "label: A.... to the next line to align with other 2 "label... lines.

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestPreorderTraversal.java
> +		expected = new String[] {"label: A, preorder_position: 1",
ditto

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +
remove newline

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> +class TraversalVisitor extends Visitor {
Add (small) comment to describe what this class is

2016-12-29 21:45 UTC, cagdasgerede commented on jtdiff/util/tests/TestTree.java
> + * Tests the functionality of Tree
This class does not test anything now. It is used to build trees to be used by its children

2017-01-02 05:52 UTC, serdarkacka commented
The issues you are referring are from commit  7e8ed9e. After that, I've submitted two more commits: fefe37f and  a5a29d6. The '>= 80 character' problems and some other style problems are solved in these commits.

2017-01-02 06:48 UTC, cagdasgerede approved these changes

2017-01-02 06:49 UTC, merged